members = Member.create([{name: "秋元真夏", image: File.open("./app/assets/images/akimotomanatu.jpg")},
                        {name: "生田絵梨花", image: File.open("./app/assets/images/ikutaerika.jpg")},
                        {name: "生田絵梨花", image: File.open("./app/assets/images/ikutaerika.jpg")},
                        {name: "生田絵梨花", image: File.open("./app/assets/images/ikutaerika.jpg")},
                        {name: "生田絵梨花", image: File.open("./app/assets/images/ikutaerika.jpg")},
                        {name: "生田絵梨花", image: File.open("./app/assets/images/ikutaerika.jpg")},
                        {name: "生駒里奈", image: File.open("./app/assets/images/akimotomanatu.jpg")},
                        {name: "伊藤万理華", image: File.open("./app/assets/images/marika_ito.jpg")},
                        {name: "井上小百合", image: File.open("./app/assets/images/inouesayuri3.jpg")},
                        {name: "衛藤美彩", image: File.open("./app/assets/images/misa_eto.jpg")},
                        {name: "川後陽菜", image: File.open("./app/assets/images/kawagohina.jpg")},
                        {name: "川村真洋", image: File.open("./app/assets/images/kawamuramahiro.jpg")},
                        {name: "齋藤飛鳥", image: File.open("./app/assets/images/saitouasuka.jpg")},
                        {name: "斎藤ちはる", image: File.open("./app/assets/images/tiharu_saito.jpg")},
                        {name: "斉藤優里", image: File.open("./app/assets/images/yuuri_saito.jpg")},
                        {name: "桜井玲香", image: File.open("./app/assets/images/reika_sakurai.jpg")},
                        {name: "白石麻衣", image: File.open("./app/assets/images/siraisimai.jpg")},
                        ])
#                         {name: "高山一実"},
#                         {name: "永島聖羅"},
#                         {name: "中田花奈"},
#                         {name: "中元日芽香"},
#                         {name: "西野七瀬"},
#                         {name: "能條愛未"},
#                         {name: "橋本奈々未"},
#                         {name: "樋口日奈"},
#                         {name: "深川麻衣"},
#                         {name: "星野みなみ"},
#                         {name: "松村沙友理"},
#                         {name: "若槻佑美"},
#                         {name: "和田まあや"},

# {name: "伊藤かりん"},{name: "伊藤純奈"},{name: "北野日奈子"},{name: "佐々木琴子"},{name: "相良伊織"},{name: "新内眞衣"},{name: "鈴木絢音"},{name: "寺田蘭世"},{name: "堀未央奈"},{name: "山崎怜奈"},{name: "渡辺みり愛"},

# {name: "伊藤理々杏"},{name: "岩本蓮加"},{name: "梅澤美波"},{name: "大園桃子"},{name: "久保史緒里"},{name: "阪口珠美"},{name: "佐藤楓"},{name: "中村麗乃"},{name: "向井葉月"},{name: "山下美月"},{name: "吉田綾乃クリスティー"},{name: "与田祐希"},

# {name: "遠藤さくら"},{name: "賀喜遥香"},{name: "掛橋沙耶香"},{name: "金川紗耶"},{name: "北川悠理"},{name: "柴田柚菜"},{name: "清宮レイ"},{name: "田村真佑"},{name: "筒井あやめ"},{name: "早川聖来"},{name: "矢久保美緒"},])
